openapi: 3.1.0

info:
  title: Gamification API
  description: Gamification 프로젝트 API 문서
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Generated server url

security:
  - bearerAuth: []

paths:

  /todos:
    post:
      tags:
        - todo-controller
      operationId: createTodo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoCreateRequest'
      responses:
        '400':
          description: Bad Request
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TodoResponse'

  /api/members/signup:
    post:
      tags:
        - member-controller
      operationId: signUp
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpRequest'
      responses:
        '400':
          description: Bad Request
        '201':
          description: Created
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/SignUpResponse'

  /api/members/logout:
    post:
      tags:
        - member-controller
      operationId: logout
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '400':
          description: Bad Request
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/LogoutResponse'

  /api/members/login:
    post:
      tags:
        - member-controller
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '400':
          description: Bad Request
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/LoginResponse'

  /api/courses/me:
    get:
      tags:
        - course-controller
      operationId: getMyCourses
      responses:
        '400':
          description: Bad Request
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MyCourseResponse'

    post:
      tags:
        - course-controller
      operationId: saveMyCourses
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SaveUserCoursesRequest'
      responses:
        '400':
          description: Bad Request
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/SaveUserCoursesResponse'

  /todos/{todoId}/complete:
    patch:
      tags:
        - todo-controller
      operationId: completeTodo
      parameters:
        - name: todoId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '400':
          description: Bad Request
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TodoResponse'

  /calendar/month:
    get:
      tags:
        - calendar-controller
      operationId: getMonthlyTodoStatus
      parameters:
        - name: memberId
          in: query
          required: true
          schema:
            type: integer
            format: int64

        - name: year
          in: query
          required: true
          schema:
            type: integer
            format: int32

        - name: month
          in: query
          required: true
          schema:
            type: integer
            format: int32

      responses:
        '400':
          description: Bad Request
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CalendarMonthResponse'

  /calendar/date:
    get:
      tags:
        - calendar-controller
      operationId: getTodosByDate
      parameters:
        - name: memberId
          in: query
          required: true
          schema:
            type: integer
            format: int64

        - name: date
          in: query
          required: true
          schema:
            type: string
            format: date

      responses:
        '400':
          description: Bad Request
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CalendarDateResponse'

  /api/members/me:
    get:
      tags:
        - member-controller
      operationId: me
      responses:
        '400':
          description: Bad Request
        '200':
          description: OK

  /api/members/check-login-id:
    get:
      tags:
        - member-controller
      operationId: checkLoginId
      parameters:
        - name: loginId
          in: query
          required: true
          schema:
            type: string

      responses:
        '400':
          description: Bad Request
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CheckLoginIdResponse'

  /api/courses/search:
    get:
      tags:
        - course-controller
      operationId: searchCourses
      parameters:
        - name: keyword
          in: query
          required: true
          schema:
            type: string

      responses:
        '400':
          description: Bad Request
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CourseSearchResponse'

  /api/courses/current:
    get:
      tags:
        - course-controller
      operationId: getCurrentCourse
      responses:
        '400':
          description: Bad Request
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CurrentCourseResponse'

  /todos/{todoId}:
    delete:
      tags:
        - todo-controller
      operationId: deleteTodo
      parameters:
        - name: todoId
          in: path
          required: true
          schema:
            type: integer
            format: int64

      responses:
        '400':
          description: Bad Request
        '200':
          description: OK

  /api/courses/me/{courseId}:
    delete:
      tags:
        - course-controller
      operationId: deleteMyCourse
      parameters:
        - name: courseId
          in: path
          required: true
          schema:
            type: integer
            format: int64

      responses:
        '400':
          description: Bad Request
        '200':
          description: OK

components:

  securitySchemes:
    bearerAuth:
      type: http
      name: bearerAuth
      scheme: bearer
      bearerFormat: JWT

  schemas:

    TodoCreateRequest:
      type: object
      properties:
        memberId:
          type: integer
          format: int64
        todoDate:
          type: string
          format: date
        title:
          type: string
        content:
          type: string

    TodoResponse:
      type: object
      properties:
        todoId:
          type: integer
          format: int64
        memberId:
          type: integer
          format: int64
        todoDate:
          type: string
          format: date
        title:
          type: string
        content:
          type: string
        isCompleted:
          type: boolean

    SignUpRequest:
      type: object
      required:
        - loginId
        - password
        - petName
      properties:
        loginId:
          type: string
          maxLength: 20
        password:
          type: string
          maxLength: 255
        petName:
          type: string
          maxLength: 10

    SignUpResponse:
      type: object
      properties:
        memberId:
          type: integer
          format: int64
        loginId:
          type: string
        petId:
          type: integer
          format: int64
        message:
          type: string
        accessToken:
          type: string
